
---
artifactory_uri: 'http://13.71.87.138:8040'

docker_wait_time: 600   # Wait for docker to pull and deploy

# Ingress is in NodePort configuration. So connect to any node cluster
ingress_nodeport_http: 30080 
ingress_nodeport_https: 300443
ingress_base_url: 'http://{{groups["kubeworkers"][0]}}:{{ingress_nodeport_http}}'

mosip_public_server: ansible1.southindia.cloudapp.azure.com
mosip_public_server_ip: 104.211.247.206

persistent_storage_node: "{{groups['kubeworkers'][0]}}" # All persistent data will be stored on this node
# CAUTTION: Assuming actual hostname and inventory hostname is same
# TODO: Another variables in hosts.ini may be defined like remote_hostname in case the two are different.
persistent_storage_hostname: '{{hostvars[persistent_storage_node]["inventory_hostname"]}}' 

