# Variable very specific to console that runs all the ansible scripts.
#
tmp_dir: '{{playbook_dir}}/tmp/'
logs_dir: '{{playbook_dir}}/logs/'

# Variables that are shared across plays (otherwise, all variables are in respective
# roles)
commons_repo_location: '{{lookup("env",  "HOME")}}/commons'
pre_reg_repo_location: '{{lookup("env",  "HOME")}}/pre-registration'
regproc_repo_location: '{{lookup("env",  "HOME")}}/registration'
