---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-nn-local-storage
spec:
  capacity:
    storage: 7Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Only this policy supported for this type of PV
  storageClassName: {{ .Values.persistence.storageClass }} 
  local:
    path: {{ .Values.persistence.namenode.hostStoragePath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - '{{mz_persistent_storage_node}}'

