---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hadoop.fullname" . }}-hdfs-nn
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: hdfs-nn
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.scName }}
spec:
  accessModes:
    - {{ .Values.persistence.nameNode.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.nameNode.size }}
