---
- include_vars: ../../config-server/defaults/main.yml 
- include_vars: ../../kernel/kernel-auth/defaults/main.yml 
- include_vars: ../../kernel/kernel-audit/defaults/main.yml 
- include_vars: ../../kernel/kernel-crypto/defaults/main.yml 
- include_vars: ../../kernel/kernel-masterdata/defaults/main.yml 
- include_vars: ../../kernel/kernel-applicant/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-batchjob/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-booking/defaults/main.yml 
- include_vars: ../../../pre-reg/pre-reg-datasync/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-demographic/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-document/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-generateqrcode/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-login/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-notification/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-transliteration/defaults/main.yml 
- include_vars: ../../pre-reg/pre-reg-ui/defaults/main.yml 

- name: Deploy ingress init 
  k8s:
    state: present
    src: '{{role_path}}/files/k8s_ingress_init.yml'
    kubeconfig: '{{kube_config}}'
    wait: 'yes'
    wait_timeout: 240 

# Deploy ingress rules 
- name: 'Ingress service - get yml from template'
  template:
     src: k8s_ingress_service.yml.j2 
     dest: '{{tmp_dir}}/k8s_ingress_service.yml'

- name: Deploy ingress service
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_ingress_service.yml'
    kubeconfig: '{{kube_config}}'
    wait: 'yes'
    wait_timeout: 240 

# Deploy ingress rules 
- name: Get yml from template 
  template:
     src: k8s_ingress.yml.j2
     dest: '{{tmp_dir}}/k8s_ingress.yml'

- name: First delete previous ingress # TODO: For some reason ingress changes are not applied otherwise 
  k8s:
    state: absent
    src: '{{tmp_dir}}/k8s_ingress.yml'
    kubeconfig: '{{kube_config}}'
    wait: 'yes'
    wait_timeout: 240 

- name: Deploy ingress rules
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_ingress.yml'
    kubeconfig: '{{kube_config}}'
    wait: 'yes'
    wait_timeout: 240 
