apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.generators.key.name }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.generators.key.name }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.generators.key.name }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.generators.key.name }} 
        component: {{ .Values.component }} 
    spec:
      containers:
      - name: {{ .Values.generators.key.name }} 
        image: {{ .Values.generators.key.dockerImage }}:{{ .Values.generators.key.dockerTag }} 
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        - name: PKCS11_PROXY_SOCKET
          value: {{ .Values.generators.key.hsmUrl }} 
