namespace: default
serviceName: softhsm

activeProfileEnv: qa
springConfigLabel: master
configServerUrl: http://config-server/config
artifactoryUrl: http://13.71.87.138:8040

docker:
  image: mosipdev/softhsm
  tag: v1

pv:
  name: softhsm-pv
  size: 20Mi 

localStorage:  # Folder on node machine
  name: softhsm-local-storage  
  hostname: mzworker0
  path: /mnt/mosip_data/softhsm

confFile: softhsm2.conf
mountPath: /softhsm

pvc:
  name: softhsm-pvc

ports:
  containerPort: 5666
  servicePort: 80

probe:
  initialDelay: 15  # Seconds
  period: 30 # Seconds
healthUrl: ''
