# This script downloads kernel config jar, builds docker and deploys it
# The docker is pushed to a local registry with SSL as Kubernetes 
# deployment needs such a registry.
---
- name: Create a tmp directory
  file:
    path: '{{tmp_dir}}'
    state: directory
    mode: '0755'

#- name: Download kernel-server-config tar
#  get_url:
#    url: '{{config_server_jar_uri}}'
#    dest: "{{role_path}}/files/{{config_server_name}}-{{config_server_version}}.jar"
#
#- name: Build docker and push it local registry  
#  docker_image:
#    name: "mosipid/sandbox-config-server"
#    tag: "{{config_server_version}}"
#    push: yes
#    source: build
#    build:
#      path: '{{role_path}}/files' 
#      pull: no 
#      args:
#        version: "{{config_server_version}}"
#        git_uri: '/mnt/mosip_data/configs/'
#        config_folder: 'mosip-infra/deployment/sandbox-v2/roles/config-gitrepo/files/properties'
#        jar_name: '{{config_server_jar_name}}'
#      #TODO: pickup gitrepo from service name

- name: Kubernetes yml file from template 
  template:
     src: k8s_config_server.yml.j2
     dest: '{{tmp_dir}}/k8s_config_server.yml'

- name: Deploy on Kubernetes
  k8s:
    src: '{{tmp_dir}}/k8s_config_server.yml'  
    state: present
    wait: yes
    wait_timeout: 120 

