---
# This script runs all the init SQL queries and populates all tables with
# test data 
# TODO: Init should not happen if Postgres has valuable data

# Get db_ip. Since Postgres is published as a node port we get the IP of any
# work node.
- name: Get postgres nodeport ip 
  command: "kubectl get node --selector='!node-role.kubernetes.io/master' -o json"
  register: out

- name: Get postgres nodeport ip 
  command: 'kubectl get service -o json postgres'
  register: out

- set_fact:
    db_port: '{{(out.stdout | from_json).spec.ports[0].nodePort}}'
 
- include: init_db.yml
  vars:
    pg_db_name: '{{item.db_name}}'
    pg_sql_path: '{{item.sql}}'
  with_items: '{{pg_databases}}'
        
