keycloak_name: keycloak
keycloak_user: admin  # Should match mosip.keycloak.admin.user.id in mosip config properites
keycloak_password: admin # Should match  mosip.keycloak.admin.secret.key in mosip config properties
keycloak_url: '{{ingress_base_url}}/{{keycloak_name}}' # To access Keycloak from outside cluster but within network. Refer ingress file.
keycloak_external_url: '{{sandbox_public_url}}/keycloak/auth' # To access keycloak from the Internet
keycloak_container_port: 8080
