# This sequence of tasks runs the required sqls and loads DB with test data
- debug:
    msg: Initialize {{item}} DB

- name: Replace IP address 
  lineinfile:
    path: '{{db_path}}/{{item}}/{{item}}_deploy.properties'
    regexp: '^DB_SERVERIP='
    line: DB_SERVERIP={{db_ip}}
   
- name: Replace Port 
  lineinfile:
    path: '{{db_path}}/{{item}}/{{item}}_deploy.properties'
    regexp: '^DB_PORT='
    line: DB_PORT={{db_port}}

- name: Replace password
  lineinfile:
    path: '{{db_path}}/{{item}}/{{item}}_deploy.properties'
    regexp: '^SU_USER_PWD='
    line: SU_USER_PWD={{db_password}}

- name: Replace base path 
  lineinfile:
    path: '{{db_path}}/{{item}}/{{item}}_deploy.properties'
    regexp: '^BASEPATH='
    line: BASEPATH={{db_path}}

- name: Replace log path 
  lineinfile:
    path: '{{db_path}}/{{item}}/{{item}}_deploy.properties'
    regexp: '^LOG_PATH='
    line: LOG_PATH={{db_log_path}}

- name: Run {{item}} shell script
  shell: 'bash {{item}}_db_deploy.sh {{item}}_deploy.properties'
  args:
    chdir: '{{ db_path }}/{{item}}'
