postgres_password: postgres
postgres_name: postgres
postgres_db: keycloak # Default DB on Postgres
postgres_user: postgres
postgres_server: '{{mz_cluster_any_node}}' # As postgres is on nodeport
# Permanent storage params
postgres_local_storage_hostname: '{{mz_persistent_storage_node}}'
postgres_container_port: 5432
