postgres_password: postgres
postgres_name: postgres
postgres_db: keycloak # Default DB on Postgres
postgres_user: postgres
postgres_external_ip: '{{groups.kubeworkers[0]}}' # Any k8s worker node since its a nodeport
# Permanent storage params
postgres_local_storage_hostname: '{{persistent_storage_hostname}}'
postgres_local_storage_path: /mnt/mosip_data/postgres
