---
# Deploy container 
- name: Get yml from template 
  template:
     src: k8s_pre_reg_datasync.yml.j2
     dest: '{{tmp_dir}}/k8s_pre_reg_datasync.yml'

- name: Deploy on kurbernetes
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_pre_reg_datasync.yml'
    wait: no
    wait_timeout: '{{docker_wait_time}}' 

