---
- name: Ensure tmp directory is present
  file: 
    path: '{{tmp_dir}}'
    state: directory

- name: Deploy ingress init 
  k8s:
    state: present
    src: '{{role_path}}/files/k8s_ingress_init.yml'
    wait: 'yes'
    wait_timeout: 240 

- name: Deploy ingress service
  k8s:
    state: present
    src: '{{role_path}}/files/k8s_ingress_service.yml'
    wait: 'yes'
    wait_timeout: 240 

# Deploy ingress rules 
- name: Get yml from template 
  template:
     src: k8s_ingress.yml.j2
     dest: '{{tmp_dir}}/k8s_ingress.yml'

- name: Deploy ingress rules
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_ingress.yml'
    wait: 'yes'
    wait_timeout: 240 
