---
- name: Deploy ingress init 
  k8s:
    state: present
    src: '{{role_path}}/files/k8s_ingress_init.yml'
    wait: 'yes'
    wait_timeout: 240 

# Deploy ingress rules 
- name: 'Ingress service - get yml from template'
  template:
     src: k8s_ingress_service.yml.j2 
     dest: '{{tmp_dir}}/k8s_ingress_service.yml'

- name: Deploy ingress service
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_ingress_service.yml'
    wait: 'yes'
    wait_timeout: 240 

# Deploy ingress rules 
- name: Get yml from template 
  template:
     src: k8s_ingress.yml.j2
     dest: '{{tmp_dir}}/k8s_ingress.yml'

- name: First delete previous ingress # TODO: For some reason ingress changes are not applied otherwise 
  k8s:
    state: absent
    src: '{{tmp_dir}}/k8s_ingress.yml'
    wait: 'yes'
    wait_timeout: 240 

- name: Deploy ingress rules
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_ingress.yml'
    wait: 'yes'
    wait_timeout: 240 
