---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.docker.image }}:{{ .Values.docker.tag }}
        env:
        - name: env_jar_name 
          value: {{ .Values.jarName }}
        - name: env_config_folder 
          value: {{ .Values.searchFolders }}
        {{ if eq .Values.localRepo.enabled true }}
        - name: env_git_uri 
          value: {{ .Values.localRepo.mountPath }}
        {{ else }}
        - name: env_git_uri 
          value: {{ .Values.gitRepoUri }}
        {{ end }}
        ports:
        - containerPort: {{ .Values.docker.containerPort }} 
        readinessProbe:
          tcpSocket:
            port: {{ .Values.docker.containerPort }}  # All defaults used
{{ if eq .Values.localRepo.enabled true }}
        volumeMounts:
        - name: repo
          mountPath: {{ .Values.localRepo.mountPath }} 
      volumes:
      - name: repo 
        persistentVolumeClaim:
          claimName: {{ .Values.localRepo.pvc.name }}
{{ end }}

