apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.component }}-ingress
  namespace: {{ .Release.Namespace}} 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /config(/|$)(.*)
        backend:
          serviceName: {{ .Values.name }} 
          servicePort: 80 

