- name: Make sure ~/.ssh is present
  file:
    path: "{{ansible_env.HOME}}/.ssh"
    state: directory
    
- name: 'Generate ssh key pair on host {{inventory_hostname}}'
  openssh_keypair:
    path: '{{ansible_env.HOME}}/.ssh/id_rsa'
    force: no
  become: yes

- authorized_key:
      user: '{{ansible_user}}'
      state: present
      key: "{{lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  become: yes
