# Source: kernel/templates/key-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsmcli 
  namespace: default 
  labels:
    app: hsmcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsmcli
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: hsmcli
    spec:
      containers:
      - name: hsmcli
        image: gsasikumar/hsmclient:v1 
        env:
        - name: active_profile_env
          value: qa
        - name: spring_config_label_env
          value: master 
        - name: spring_config_url_env
          #value: http://104.211.212.28:51000
          value: http://config-server/config
        - name: ARTIFACTORY_URL 
          value: http://13.71.87.138:8040 
        - name: PKCS11_PROXY_SOCKET
          #value: tcp://10.244.1.43:5666
          value: tcp://softhsm:80
