---
# The tasks here update a property in a given property file and check-in
# the updated file in config git repo

- name: 'Update {{property}} in {{property_file}} in git repo' 
  lineinfile:
    path: '{{config_gitrepo}}/{{property_file}}'
    regexp: '^{{property}}\s?=.*$'
    line: '{{property}}={{value}}' 
  
- name: Check-in updated property file in git repo 
  shell: 'git -c user.email="{{ansible_user_id}}@mosip" commit -m "Updated" {{property_file}}'
  args:
    chdir: '{{config_gitrepo}}' 
  ignore_errors: true
 

