---
ansible_python_interpreter: /usr/bin/python3

ansible_become_password: puneet  # For commands that require sudo

tmp_dir: '{{playbook_dir}}/tmp/'
logs_dir: '{{playbook_dir}}/logs/'

artifactory_uri: 'http://13.71.87.138:8040'

postgres_password: postgres
postgres_db: keycloak # Default DB on Postgres
postgres_user: postgres
postgres_external_ip: '{{hostvars[groups.kubeworkers[0]].ansible_host}}'

keycloak_user: admin
keycloak_password: admin
