namespace: default
component: idrepo
part-of: mosip
activeProfileEnv: qa
springConfigLabel: master
configServerUrl: http://config-server/config
ingress:
   namespace: default
artifactoryUrl: http://13.71.87.138:8040
probe:
  initialDelay: 30  # Seconds
  period: 30 # Seconds
services:
  identity:
    serviceName: idrepo-identity-service
    dockerImage: mosipdev/id-repository-identity-service
    dockerTag: 1.0.9
    containerPort: 8090
    servicePort: 80
    ingressPath: /idrepository/v1/identity 
    healthUrl: /idrepository/v1/identity/actuator/health
  vid: 
    serviceName: idrepo-vid-service
    dockerImage: mosipdev/id-repository-vid-service
    dockerTag: 1.0.9
    containerPort: 8091
    servicePort: 80
    ingressPath: /idrepository/v1/vid
    healthUrl: /idrepository/v1/actuator/health
