apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
     kubernetes.io/ingress.class: "nginx"
    # nginx.com/health-checks: "true"
spec:
  rules:
  - http:
      paths:
      - path: /activemq
        backend:
          serviceName: {{ .Values.name }}
          servicePort: 80
