---
# Creates folder in nfs for reg-client to provide metadata.xml and mosip-cer file.
# These files are further used by reg-client downloader to create the client zip.

- name: Create reg client folder in nfs.
  file:
    path: '{{reg_prop.nfs_path}}'
    state: directory 
  become: yes

- name: Copy certificate
  copy:
    src: '{{reg_prop.cert_path}}/{{reg_prop.cert_file}}'
    dest: '{{reg_prop.nfs_path}}' 
    force: no
  become: yes
  
- name: Copy metadata.xml
  copy:
    src: '{{reg_prop.xml_file}}' 
    dest: '{{reg_prop.nfs_path}}'
    force: no
  become: yes
