---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvcName }}
  labels:
    app: {{ .Values.pvcName }} 
spec:
  storageClassName: {{ .Values.localStorageName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: {{ .Values.pvName }} 

