---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvcName }} 
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.scName }} 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 
