---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: default

spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80 
      targetPort: {{ .Values.containerPort }}
