# Creates folder on a node for softhsm
# These tasks are applicable on the node on which
# folders are located.
- name: Create softhsm folder
  file:
    path: '{{hsm_prop.local_folder}}'
    state: directory 

- name: Copy conf file
  copy:
    src: '{{hsm_prop.conf_path}}'
    dest: '{{hsm_prob.local_folder}}' 
  
- name: Copy base tokens
  copy:
    src: '{{hsm_prop.tokens_path}}' 
    dest: '{{softhsm_storage_folder}}'
    force: no


