# Params:
#   ansible_var
#   target_file
#   target_var

- name: 'Updating {{target_var}} in {{target_file}}'
  lineinfile:
    path: '{{target_file}}' 
    regexp: '^{{target_var}}'
    line: '{{target_var}}: {{target_value}}'

