name: postgres
password: postgres
defaultDb: keycloak # Default DB on Postgres
user: postgres
containerPort: 5432
pvcName: postgres-pvc
scName: nfs-storage # Must match with NFS install name
pvSize: 1Gi
dockerImage: postgres
dockerTag: 12.2
nodePort: 30090
maxConnections: 1000 
