# These tasks create user directories on HDFS and assign them full
# ownership
#
- name: 'Create directory for {{hdfs_user}}'
  command: 'kubectl exec -it {{hdfs_pod_id}} -- /bin/bash -c "/usr/local/hadoop/bin/hdfs dfs -mkdir -p {{hdfs_user_dir}}"' 

- name: 'Give permissions to {{hdfs_user}}' 
  command: 'kubectl exec -it {{hdfs_pod_id}} -- /bin/bash -c "/usr/local/hadoop/bin/hdfs dfs -chown -R {{hdfs_user}}:{{hdfs_user}} {{hdfs_user_dir}}"' 
