---
# Deploy on kubernetes 
- name: Ensure tmp directory is present
  file: 
    path: '{{tmp_dir}}'
    state: directory

# Deploy container 
- name: Get yml from template 
  template:
     src: k8s_pre_reg_login.yml.j2
     dest: '{{tmp_dir}}/k8s_pre_reg_login.yml'

- name: Deploy on kurbernetes
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_pre_reg_login.yml'
    wait: 'yes'
    wait_timeout: '{{docker_wait_time}}' 

