---
- hosts: '{{cluster_name}}'
  become: yes
  gather_facts: yes
  roles:
    - { role: k8scluster/docker, tags: docker }
    - { role: packages/git, tags: git }

- hosts: '{{cluster_name[0]}}'  # Master 
  gather_facts: yes
  become: yes
  roles:
    - { role: k8scluster/kubernetes/master, tags: master }
    - { role: k8scluster/cni, tags: cni }

- hosts: '{{cluster_name[0][1]}}' # Workers
  gather_facts: yes
  become: yes
  roles:
    - { role: k8scluster/kubernetes/node, tags: node }

- hosts: '{{cluster_name[0]}}'  # Master 
  gather_facts: yes
  become: yes
  tasks:
    - name: "MetalLB role"
      include_role:
        name: k8scluster/metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Healthcheck role"
      include_role:
        name: k8scluster/healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck

