## Playbook to create dmz cluster
- import_playbook: cluster.yml
  vars:
    cluster: dmzcluster
    master: dmzmaster
    workers: dmzworkers

# Install dashboard
- hosts: console
  vars:
    kube_config: '{{clusters.dmz.kube_config}}' 
    cluster_name: 'dmz'
    dashboard_ingress_url: '{{clusters.dmz.dashboard.url}}'
  roles:
    - {role: k8scluster/dashboard}

