# Playbook to install ELK stack (actually EFK!)
# Currently only installed 

# Install Elasticsearch
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: elasticsearch 
    helm_chart: '{{charts_root}}/elasticsearch'
    is_template: false
    helm_namespace: default
    helm_values: '{{charts_root}}/elasticsearch/values.yaml'
  roles:
    - {role:  helm}

# Install Kibana
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: kibana
    helm_chart: '{{charts_root}}/kibana'
    is_template: false
    helm_namespace: default
    helm_values: '{{charts_root}}/kibana/values.yaml'
  roles:
    - {role:  helm}

# Install Filebeat
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: filebeat
    helm_chart: '{{charts_root}}/filebeat'
    is_template: false
    helm_namespace: default
    helm_values: '{{charts_root}}/filebeat/values.yaml'
  roles:
    - {role:  helm}
