# Installs HDFS.

- hosts: console
  gather_facts: true
  vars:
    kube_config: '{{mz_kube_config}}'  # Deploy all these on mz cluster
  roles:
     - {role: helm, install_name: 'hadoop', helm_chart: '{{charts_root}}/hadoop', tags: [hdfs]}
     - {role: hdfs-init,  tags: [hdfs-init]}

