- import_playbook: softhsm.yml 
  vars:
    hsm_prop: '{{softhsm.ida}}'

- hosts: console
  gather_facts: true
  vars:   
    kube_config: '{{clusters.mz.kube_config}}' 
    helm_chart: '{{charts_root}}/ida'
    install_name: ida
  roles:
    - {role: helm, tags: [ida]} 
