- hosts: console
  gather_facts: true
  vars:   
    kube_config: '{{clusters.mz.kube_config}}' 
    helm_chart: '{{charts_root}}/idrepo'
    install_name: idrepo
  roles:
    - {role: helm, tags: [idrepo]} 
