# This play installs all Kernel services using Helm

# Softhsm is needed for Keymanager
- import_playbook: softhsm.yml 
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    hsm_prop: '{{softhsm.keymanager}}'

# Run all kernel services
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'kernel'
    helm_chart: '{{charts_root}}/kernel'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/kernel/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}

# Init master keys. 
# This is done using a temporary python script. NOT to be done in this
# fashion on production.  TODO: move to docker init instead of this script.
#
- hosts: console
  gather_facts: false
  tasks:
    - name: Initialize master keys of keymanager
      shell: './utils/init_keys.py {{sandbox_domain_name}}'
      args:
        chdir: '{{install_root}}'
