# This play installs all Kernel services using Helm
- hosts: mzworker0
  gather_facts: true
  roles:
    - {role: softhsm, tags: [softhsm]}

- hosts: console
  gather_facts: true
  vars:   
    kube_config: '{{mz_kube_config}}' 
    helm_chart: '{{charts_root}}/kernel'
    install_name: kernel
  roles:
    - {role: helm, tags: [kernel]} 
