## Playbook to create mz cluster
- import_playbook: cluster.yml
  vars:
    cluster: mzcluster
    master: mzmaster
    workers: mzworkers

# Install dashboard
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    cluster_name: 'mz'
    dashboard_ingress_url: '{{clusters.mz.dashboard.url}}'
  roles:
    - {role: k8scluster/dashboard}

- import_playbook: monitoring.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    mon_prop: '{{clusters.mz.monitoring}}' 
  

