# MZ cluster
- import_playbook: cluster.yml
  vars:
    cluster: mzcluster
    master: mzmaster
    workers: mzworkers

# Kubenetes dashboard
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    cluster_name: 'mz'
    dashboard_ingress_url: '{{clusters.mz.dashboard.url}}'
  roles:
    - {role: k8scluster/dashboard}

# Prometheus
- import_playbook: prometheus.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    mon_prop: '{{clusters.mz.monitoring}}' 

# Grafana
- import_playbook: grafana.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    mon_prop: '{{clusters.mz.monitoring}}' 
  

