---
- hosts: mzcluster
  become: yes
  gather_facts: yes
  roles:
    - { role: k8scluster/docker, tags: docker }
    - { role: packages/git, tags: git }

- hosts: mzmaster
  gather_facts: yes
  become: yes
  roles:
    - { role: k8scluster/kubernetes/master, tags: master }
    - { role: k8scluster/cni, tags: cni }

- hosts: mzworkers 
  gather_facts: yes
  become: yes
  roles:
    - { role: k8scluster/kubernetes/node, tags: node }

- hosts: mzmaster
  gather_facts: yes
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
        name: k8scluster/helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm

    - name: "MetalLB role"
      include_role:
        name: k8scluster/metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Healthcheck role"
      include_role:
        name: k8scluster/healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck

