# MZ cluster
- import_playbook: cluster.yml
  vars:
    cluster: mzcluster
    master: mzmaster
    workers: mzworkers

# Ingress nginx controller
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'ingress-nginx'
    helm_chart: '{{charts_root}}/ingress-nginx'
    is_template: false
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/ingress-nginx/values.yaml'
  roles:
    - {role:  helm, tags: [mz-ingress]}

# Kubenetes dashboard
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    cluster_name: 'mz'
    dashboard_ingress_url: '{{clusters.mz.dashboard.url}}'
  roles:
    - {role: k8scluster/dashboard}

# Prometheus
- import_playbook: prometheus.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    mon_prop: '{{clusters.mz.monitoring}}' 

# Grafana
- import_playbook: grafana.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    mon_prop: '{{clusters.mz.monitoring}}' 
  

