
---
# Global variables - accessed by different roles and plays
#

sandbox_domain_name: test-sandbox.southindia.cloudapp.azure.com 
sandbox_public_url: 'https://{{sandbox_domain_name}}'

ssl:
  get_certificate: true  # get a fresh certificate for the domain using Letsencrypt.
  email: info@mosip.io
  certificate: '/etc/letsencrypt/live/{{sandbox_domain_name}}/fullchain.pem'
  certificate_key: '/etc/letsencrypt/live/{{sandbox_domain_name}}/privkey.pem'

install_root: /home/mosipuser/mosip-infra/deployment/sandbox-v2
charts_root: '{{install_root}}/helm/charts'  # Helm charts root

artifactory_uri: 'http://13.71.87.138:8040'

docker_wait_time: 600   # Wait for docker to pull and deploy

# Any of the worker nodes of a cluster may be used to access nodeport
mz_cluster_any_node: '{{groups["mzworkers"][0]}}'
dmz_cluster_any_node: '{{groups["dmzworkers"][0]}}'

# Config files
mz_kube_config: "{{lookup('env', 'HOME') }}/.kube/mzcluster.config" 
dmz_kube_config: "{{lookup('env', 'HOME') }}/.kube/dmzcluster.config" 

# Ingress is in NodePort configuration. So connect to any node cluster
mzingress:
  nodeport_http: 30080  # TODO: Shoud match with helm
  nodeport_https: 30443
  base_url: 'http://{{mz_cluster_any_node}}:30080' # Same as nodeport_http

mz_persistent_storage_node: mzworker0  # All persistent data in MZ will be stored on this node. TODO: this should match helm

# Registration processor shared variables
#
regproc:
  landing_folder: /mnt/regproc/landing 
  landing_hostname: dmzworker0  # Should be same one used in creating these folders (see regproc.yml) 

# Postgres persistent storage
postgres:
  local_storage_path: /mnt/mosip_data/postgres  # TODO: This should match with helm charts
  server: '{{mz_cluster_any_node}}' # Since postgres runs on node port
  nodeport: 30090  # fixed for connecting from outside the cluster
  user: postgres
  password: postgres

# hdfs dn and nn
hdfs_dn_local_storage_path: /mnt/mosip_data/hdfs/dn
hdfs_nn_local_storage_path: /mnt/mosip_data/hdfs/nn

# Config server
config_server_local_storage_path: /mnt/mosip_data/
config_server_external_url: '{{ingress_base_url}}/config'

# Softhsm storage dir
softhsm_storage_folder: /mnt/mosip_data/softhsm

# SFTP: used for picking up packets from DMZ
sftp_user: 'sftpuser'  # This should be same in config files

# Keycloak
keycloak:
  user: admin
  password: admin
  url: '{{mzingress.base_url}}/keycloak'
