# This script has common tasks related to deployment that can 
# be called to deploy any Kubernetes "Deployment" yml.
# Make sure you set the following before including this task:
#   deployment_yml_path
#   deployment_name  
---
- name: Deploy on Kurbernetes
  command: 'kubectl apply -f {{deployment_yml_path}}'

- name: Check status of deployment
  command: 'kubectl rollout status deployment/{{deployment_name}}'
  register: result
  until: result.stdout.find('successfully rolled out') != -1
  retries: 5
  delay: 5 

