---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.ui.appName}}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.ui.appName}}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{.Values.ui.appName}}
    spec:
      containers:
      - name: {{.Values.ui.appName}}
        image: {{ .Values.ui.dockerImage  }}:{{ .Values.ui.dockerTag }}
        ports:
        - containerPort: {{ .Values.ui.containerPort }} 
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ui.containerPort }}  # All defaults used
        volumeMounts:
            - name: ui-config 
              mountPath: /usr/share/nginx/html/assets/config.json
              # The above path is fixed in Dockerfile
              subPath: config.json #TODO: subPath is needed.  Check why
              # The config map gets mounted like files where key=file, value=file contents
      volumes:
        - name: ui-config
          configMap:
            name: {{ .Values.ui.configName }}
