---
  - hosts: all
    become: 
    tasks:  
      - name: Deploying docker secret registry
        k8s:
          state: present
          definition: "{{ lookup('file', '../kubernetes/commons/docker-registry-secret.yml') }}"