---
  - hosts: all
    become: true
    tasks:
      - set_fact:
          VMIP: "{{ hostvars[groups['SandboxVM'][0]]['VMIP'] }}"

      - name: Changing Pre Reg base url in properties
        replace:
          path: ../kubernetes/pre-registration/pre-registration-ui-configuration.yml
          regexp: '<yourPublicIp>'
          replace: "{{ VMIP }}"

      - name: Finding all the Pre registration ymls
        find:
          paths: ../kubernetes/pre-registration
          patterns: '*.yml'
          recurse: yes
        register: paths_pre_registration_ymls

      - name: Deploying all the Pre Registration Modules
        k8s:
          state: present
          src: "{{ item.path }}"
        with_items: "{{ paths_pre_registration_ymls.files }}"