# These tasks create a role inside a realm
- name: Create role inside realm 
  uri:
    url: '{{keycloak_url}}/auth/admin/realms/{{realm_id}}/roles'
    method: POST
    src: '{{role_file}}'
    remote_src: 'no'
    status_code:
     - 201
    headers:
      Content-type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{keycloak_admin_token}}"
