
- name: 'Find out, if Realm {{realm_name}} exists'
  uri:
    url: "{{keycloak_url}}/auth/admin/realms/{{keycloak_realm_name}}"
    method: GET
    status_code:
     - 200
     - 404
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{keycloak_admin_token}}"
  register: keycloak_realm_exists

- debug:
     msg: 'Realm {{keycloak_realm_name}} exists: {{keycloak_realm_exists.status}}' 

- name: 'Create Realm {{keycloak_realm_name}}' 
  uri:
    url: '{{keycloak_url}}/auth/admin/realms'
    method: POST
    src: '{{keycloak_realm_data_file}}'
    remote_src: 'no'
    status_code:
     - 201
    headers:
      Content-type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{keycloak_admin_token}}"
  register: keycloak_realm_create
  when: "keycloak_realm_exists.status == 404"

- name: 'Update Realm {{keycloak_realm_name}} for service Keycloak'
  uri:
    url: '{{keycloak_url}}/auth/admin/realms/{{keycloak_realm_name}}'
    method: PUT
    src: "{{keycloak_realm_data_file}}"
    remote_src: "no"
    status_code:
     - 204
    headers:
      Content-type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{keycloak_admin_token}}"
  register: keycloak_realm_create
  when: "keycloak_realm_exists.status == 200"
