---
- name: Get port of keycloak service
  k8s_info:
    api_version: v1
    kind: Service
    name: keycloak 
    namespace: default 
  register: web_service

- name: Get nodePort and create url 
  set_fact: 
    keycloak_url: 'http://{{kubeworkers.worker1.ip}}:{{web_service.resources[0].spec.ports[0].nodePort}}'

- name: "Get admin token"
  uri:
    url: "{{keycloak_url}}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      username: '{{keycloak_user}}'
      password: '{{keycloak_password}}' 
      grant_type: "password"
      client_id: "admin-cli"
  register: keycloak_token

- set_fact:
    keycloak_admin_token: '{{keycloak_token.json.access_token}}'


- include_tasks:
    file: create_client.yml
  vars:
      realm_id: '{{item.realm_id}}'   
      client_id: '{{item.client_id}}'
  with_items:
  - {realm_id: 'mosip', client_id: 'test_cli'} 

- include_tasks:
    file: create_realm.yml
  vars:
    keycloak_realm_name: '{{item.realm_name}}' 
    keycloak_realm_data_file: '{{item.realm_file}}'
  with_items:
  - {realm_name: 'mosip', realm_file: 'realm_mosip.json'}
