---
- hosts: console
  roles:
     - postgres 
     - {role: postgres-init, tags: postgres-init}
     - local-registry
     - config-gitrepo
     - config-server
     - keycloak
     - keycloak-init
     - kernel-auth
     - {role: pre-reg/pre-reg-login, tags: pre-reg-login}

