---
- hosts: console
  gather_facts: false
  # Note: we have put tags here to run roles individually if needed.
  roles:
     - {role: config-server, tags: config-server}
     - {role: postgres, tags: postgres}
     - {role: postgres-init, tags: postgres-init} 
     - keycloak
     - keycloak-init
     - {role: kernel/kernel-auth, tags: kernel-auth} 
     - {role: kernel/kernel-emailnotification, tags: kernel-emailnotification}
     - {role: pre-reg/pre-reg-login, tags: pre-reg-login}
     - {role: pre-reg/pre-reg-notification, tags: pre-reg-notification}
     - {role: pre-reg/pre-reg-ui, tags: pre-reg-ui}

