---
# Deploy postgress kubernetes
## Create persistent storage
- name: Get persistent storage yml from template 
  template:
     src: k8s_pg_storage.yml.j2
     dest: '{{tmp_dir}}/k8s_pg_storage.yml'

- name: Deploy persistent storage on kurbernetes
  k8s:
    namespace: default
    state: present
    src: '{{tmp_dir}}/k8s_pg_storage.yml'
    kubeconfig: '{{kube_config}}'

# Deploy postgres container 
- name: Get postgres yml from template 
  template:
     src: k8s_postgres.yml.j2
     dest: '{{tmp_dir}}/k8s_postgres.yml'

- name: Deploy postgres on kurbernetes
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_postgres.yml'
    wait: 'yes'
    kubeconfig: '{{kube_config}}'
    wait_timeout: '{{docker_wait_time}}' 
