apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.services.pktserver.pvName }} 
  labels:
    name: {{ .Values.services.pktserver.pvName }} 
spec:
  capacity:
    storage: {{ .Values.services.pktserver.pvSize }} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Only this policy supported for this type of PV 
  storageClassName: {{ .Values.storageClass }}
  local:
    path: {{ .Values.services.pktserver.pvPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.services.pktserver.pvHostName }} # The node on which pv_path directory exists
