apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.email.serviceName }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.services.email.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.email.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.email.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      containers:
      - name: {{ .Values.services.email.serviceName }} 
        image: {{ .Values.services.email.dockerImage }}:{{ .Values.services.email.dockerTag }} 
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        ports:
        - containerPort: {{ .Values.services.email.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.email.healthUrl }} 
            port: {{ .Values.services.email.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
          timeoutSeconds: 5  # TODO: Only done for this service as it takes some time for the probe to respond. Do for all.
        livenessProbe:
          httpGet:
            path: {{ .Values.services.email.healthUrl }} 
            port: {{ .Values.services.email.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }}
          timeoutSeconds: 5
