apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.softhsm.serviceName }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.services.softhsm.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.softhsm.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.softhsm.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      containers:
      - name: {{ .Values.services.softhsm.serviceName }} 
        image: {{ .Values.services.softhsm.dockerImage }}:{{ .Values.services.softhsm.dockerTag }} 
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        ports:
        - containerPort: {{ .Values.services.softhsm.containerPort }}
        readinessProbe:  #Since no actuator, we watch tcp port.
          tcpSocket:
            port: {{ .Values.services.softhsm.containerPort }}
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
        livenessProbe:
          tcpSocket:
            port: {{ .Values.services.softhsm.containerPort }}
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
        volumeMounts:
        - name: hsm-data
          mountPath: /softhsm # See notes above
      volumes:
      - name: hsm-data
        persistentVolumeClaim:
          claimName: {{ .Values.services.softhsm.pvcName }} 
