# Reset config repo
- hosts: '{{cluster}}' 
  gather_facts: no
  become: yes
  vars_prompt:
    - name: sure 
      prompt: 'Do you want to ERASE CONFIG REPO? Are you sure?' 
      private: no
  tasks:
    - name: Delete config repo  
      block:
        - name: Include vars 
          include_vars: '{{install_root}}/roles/config-repo/defaults/main.yml'
    
        - name: Delete config repo
          file: 
            path: '{{config_repo_node_path}}/'
            state: absent     
      when: sure.lower().strip() == 'yes'
