- hosts: '{{cluster}}'
  gather_facts: no
  become: yes
  vars_prompt:
    - name: sure 
      prompt: 'Do you want to ERASE all SOFTHSM keys and data? Are you sure?'
      private: no
  tasks:
   - name: Delete all softhsm  data 
     file: 
       path: '{{softhsm_base_path}}/'
       state: absent     
     when: sure.lower().strip() == 'yes'
