---
# This script runs all the init SQL queries and populates all tables with
# test data 

- hosts: all
  tasks:
    - name: Include vars
      include_vars: pg_config.yml
   
    - name: Create logs directory
      file:
        path: "{{db_log_path}}"
        state: directory
        mode: '0755'

    - include: init_db.yml
      with_items:
        - mosip_kernel
        
