---
# This script runs all the init SQL queries and populates all tables with
# test data 

- hosts: all
  tasks:
    - name: Include vars
      include_vars: pg_config.yml

    - name: Replace IP address 
      lineinfile:
        path: "{{db_path}}/mosip_master/mosip_master_deploy.properties"
        regexp: '^DB_SERVERIP='
        line: DB_SERVERIP={{db_ip}}
   
    - name: Replace Port 
      lineinfile:
        path: "{{db_path}}/mosip_master/mosip_master_deploy.properties"
        regexp: '^DB_PORT='
        line: DB_PORT={{db_port}}

    - name: Run mosip_master shell script 
      shell: bash mosip_master_db_deploy.sh mosip_master_deploy.properties 
      args:
        chdir: "{{ db_path }}/mosip_master"
