# This play installs all the MOSIP related modules on Kubernetes
# cluster 
- hosts: console
  gather_facts: true
  vars_files:
    - ../roles/config-server/defaults/main.yml 
  vars:
    kube_config: '{{mz_kube_config}}'  # Deploy all these on mz cluster
    kubeconfig: '{{mz_kube_config}}'  # Used in k8s role. TODO: Make it consistent so that only one variable is needed.
  roles:
     - {role: kernel/kernel-auth, tags: [kernel-auth, kernel]}  
     - {role: kernel/kernel-audit, tags: [kernel-audit, kernel]} 
     - {role: kernel/kernel-masterdata, tags: [kernel-masterdata, kernel]} 
     - {role: kernel/kernel-email, tags: [kernel-email, kernel]}
     - {role: kernel/kernel-otp, tags: [kernel-otp, kernel]}
     - {role: kernel/kernel-prid, tags: [kernel-prid, kernel]}
     - {role: kernel/kernel-crypto, tags: [kernel-crypto, kernel]}
     - {role: kernel/kernel-key, tags: [kernel-key, kernel]}
     - {role: kernel/kernel-applicant, tags: [kernel-applicant, kernel]}

