---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    app: {{ .Values.pvc.name }} 
spec:
  storageClassName: {{ .Values.sc.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.size }}  # Same as pv
  selector:
    matchLabels:
      name: {{ .Values.pv.name }} 

