---
- name: "Get Helm installer"
  unarchive:  
    src: '{{ helm_download_url }}'
    dest: '{{ tmp_dir }}'
    remote_src: yes

- name: "Copy Helm executable"
  copy:
    src: '{{ tmp_dir }}/linux-amd64/helm' 
    dest: /usr/local/bin
    mode: 0755
  become: yes

- name: "Copy yaml file"
  copy:
    src: "rbac-config.yml"
    dest: "{{tmp_dir}}/rbac-config.yml"
    mode: 0644

- name: "Deploy RBAC configuration"
  k8s:
    state: present
    src: '{{tmp_dir}}/rbac-config.yml'
    kubeconfig: '{{kube_config}}'
    wait: yes
    wait_timeout: '{{docker_wait_time}}'

- name: "Init Helm"
  shell: "helm --kubeconfig {{kube_config}} init --service-account tiller"

- name: "Update Helm repo"
  shell: "helm repo update"

