---

# Deploy Keycloak kubernetes
- include_vars:
    file: ../../../postgres/postgres/defaults/main.yml

# Deploy Keycloak container 
- name: Get yml from template 
  template:
     src: k8s_keycloak.yml.j2
     dest: '{{tmp_dir}}/k8s_keycloak.yml'

- name: Deploy Keycloak on Kurbernetes
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_keycloak.yml'
    kubeconfig: '{{kube_config}}'
    wait: 'yes'
    wait_timeout: '{{docker_wait_time}}'
