# Tasks to update nginx conf file and restart nginx
#
- name: nginx conf template {{nginx_conf_template}} to yml 
  template:
    src: '{{nginx_conf_template}}'
    dest: '{{tmp_dir}}/nginx.conf'

- name: Copy new conf file
  copy:
    src: '{{tmp_dir}}/nginx.conf'
    dest: '/etc/nginx'
  become: yes

- name: Restart nginx
  command: 'systemctl restart nginx'
  become: yes
