---
# Deploy on kubernetes 
- name: Ensure tmp directory is present
  file: 
    path: '{{tmp_dir}}'
    state: directory

# Deploy ConfigMap 
- name: Get yml from template 
  template:
     src: k8s_pre_reg_config.yml.j2
     dest: '{{tmp_dir}}/k8s_pre_reg_config.yml'

- name: Deploy configmap on kurbernetes
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_pre_reg_config.yml'
    wait: 'yes'
    wait_timeout: 120 

# Deploy UI container
- name: Get yml from template 
  template:
     src: k8s_pre_reg_ui.yml.j2
     dest: '{{tmp_dir}}/k8s_pre_reg_ui.yml'

- name: Deploy ui on kurbernetes
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_pre_reg_ui.yml'
    wait: 'yes'
    wait_timeout: 120 

