---
# Deploy ConfigMap 
- name: Get yml from template 
  template:
     src: k8s_pre_reg_config.yml.j2
     dest: '{{tmp_dir}}/k8s_pre_reg_config.yml'

- name: Deploy configmap on kurbernetes
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_pre_reg_config.yml'
    wait: 'yes'
    wait_timeout: '{{docker_wait_time}}' # Make sure config map is set
 
# Deploy UI container
- name: Get yml from template 
  template:
     src: k8s_pre_reg_ui.yml.j2
     dest: '{{tmp_dir}}/k8s_pre_reg_ui.yml'

- name: Deploy ui on kurbernetes
  k8s:
    state: present
    src: '{{tmp_dir}}/k8s_pre_reg_ui.yml'
    wait: no
    wait_timeout: '{{docker_wait_time}}'

