namespace: default
component: resident
part-of: mosip
activeProfileEnv: qa
springConfigLabel: master
configServerUrl: http://config-server/config
ingress:
   namespace: default
artifactoryUrl: http://13.71.87.138:8040
probe:
  initialDelay: 30  # Seconds
  period: 30 # Seconds
services:
  resident: 
    serviceName: resident-service
    dockerImage: mosipdev/resident-service
    dockerTag: 1.0.9
    containerPort: 8099
    servicePort: 80
    ingressPath: /resident/v1
    healthUrl: /resident/v1/actuator/health
